### ISSUE TITLE
to-do's from presentation template walk-through

### ISSUE THREAD

**Issue by crestonesoftware** [maucap20/poke-search#41]
- [ ] create user stories
- [ ] create issues that implement each user story
- [ ] move base URL to common, add end separately

Thoughts
- presentation template looks like it would work well for a much more involved project (project 2 or 3)
- looks like overkill for this first, simple project. E.G. this project is about making something simple work - I don't expect to have interesting code highlights and I feel good about that.
-
